### ISSUE TITLE
Documentation and usage instructions

### ISSUE THREAD

**Issue by chesney** [katharostech/cast2gif#1]
Hi,

Thank You for this project that you created. I had fun learning rust and how to compile the application. I want to request that you add a few instructions in the README file to help others on how to compile the application and how to use it.

Regards

**Comment by zicklag** [comment]
Hey there! Glad that you like it. :smiley:

It is still kind of broken at the moment, just a warning, but a proper README would a good idea. I'll probably take a look at this soon. Feel free to ping me again here if a week or so goes by and I don't do it. :wink:

**Comment by zicklag** [comment]
There you go @chesney, looks a lot nicer now. Thanks for the issue!
