### ISSUE TITLE
Failed to buld cast2gif

### ISSUE THREAD

**Issue by piaoger** [katharostech/cast2gif#2]
```
error[E0432]: unresolved import `font_kit::loaders::freetype`
 --> src/frame_renderer/fontkit.rs:6:14
  |
6 |     loaders::freetype::Font,
  |              ^^^^^^^^ could not find `freetype` in `loaders`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `cast2gif`.
```

Env:  
```
stable-x86_64-apple-darwin (default)
rustc 1.43.0 (4fb7144ed 2020-04-20)
```

**Comment by piaoger** [comment]
add a link to [asciinema issue](https://github.com/LegNeato/asciinema-rs/issues/36)
@zicklag

**Comment by zicklag** [comment]
Hmm, that's strange. Oh, it must have something to do with building on Darwin. I haven't tried that yet. 

I'll have to check whether or not there is a cross-platform option or a way to enable freetype in Darwin builds.

**Comment by zicklag** [comment]
I'll test it and push an update when I get the chance, but if you want to you can try adding the `loader-freetype` feature to the freetype dependency in the `Cargo.toml`.

**Comment by zicklag** [comment]
Oh :facepalm: I don't actually have a Mac to test on, so if you could test that change for me that would be great. :smiley:

**Comment by piaoger** [comment]
Works find after the change 👍

**Comment by zicklag** [comment]
Awesome, thanks for testing! If you want you could open a PR to be marked as a contributor. :smiley:

Otherwise I'll push the update when I get the chance.
