### ISSUE TITLE
Cursor not rendered in GIF

### ISSUE THREAD

**Issue by pR0Ps** [katharostech/cast2gif#6]
The cursor is not rendered in the converted GIF

Example ([source cast](https://asciinema.org/a/349330)):

asciinema.org
![asciinema.org](https://user-images.githubusercontent.com/466941/88591638-a42f7980-d02a-11ea-9f7f-c6855ead3759.png)
cast2gif
![cast2gif](https://user-images.githubusercontent.com/466941/88591639-a4c81000-d02a-11ea-8b77-ce0048dfb7cd.png)

**Comment by zicklag** [comment]
Hey there, thanks for the issue, that shouldn't be too hard to fix.

We just need to add a step that adds a filled square for the cursor position similar to how we do [here](https://github.com/katharostech/cast2gif/blob/8d572ac8f5ed06def2c4197737dac9824d5586f5/src/frame_renderer/fontkit.rs#L92) for all of the background cells.

I might get to that later tonight or over the weekend. Feel free to ping me here if I don't.

**Comment by zicklag** [comment]
I just pushed a commit that adds the cursor rendering:

![recording](https://user-images.githubusercontent.com/25393315/89246621-27277580-d5d1-11ea-9435-bddff868149c.gif)

The cursor color behaviour may not be normal. I just reverse the background and foreground colors in the cell that the cursor is in. I'm not exactly sure how terminal emulators usually handle that and I'm open to changing it if you want it different. ☺

**Comment by pR0Ps** [comment]
I think it's the terminal emulator itself that controls how to render the cursor (colors, styles, etc) but what you've done here is a good general-case implementation. Thank you!
