### ISSUE TITLE
cast2gif crashes on FreeBSD

### ISSUE THREAD

**Issue by nunotexbsd** [katharostech/cast2gif#8]
Hello,

I've compiled cast2gif on FreeBSD 12.2 (amd64) using Rust 1.47.0 without any warnings/errors.

I got an error/crash when I execute:
`./cast2gif ~/test.cast /tmp/test.gif`
`Illegal instruction (core dumped)`

What should I do to help debugging this problem?

Thanks,

Nuno Teixeira

**Comment by zicklag** [comment]
Oh, that's pretty strange. I wonder if there's something broken in the build steps for one of the native dependencies like freetype or something on FreeBSD. I've only tested it on Ubuntu, but we shouldn't get illegal instructions without `unsafe` in the Rust code.

Anyway, I just created a statically linked build with no system dependencies and published a pre-release for it. It works for me and doesn't link to anything on the system so it *should* work for you:

https://github.com/katharostech/cast2gif/releases/tag/pre-release

If you aren't wanting to develop `cast2gif` itself, then that should be a workable solution for you. :slightly_smiling_face:

**Comment by nunotexbsd** [comment]
I've compiled pre-release and I get same error and I've tested other rust programs without problems.
Could you please test it on a VM while I write a FreeBSD port so I get more help and people to test it?

Only 5 minute task:

- Choose a VM [disk image](https://download.freebsd.org/ftp/releases/VM-IMAGES/12.2-RELEASE/) of choice
- run as root:
`pkg install rust`
- download cast2gif and compile

Could you please do that?

Thanks

**Comment by zicklag** [comment]
Were you able to download and run the program from the release?

https://github.com/katharostech/cast2gif/releases/download/pre-release/cast2gif

> Only 5 minute task:

I'll try that if I get the chance, but if the release works do you still need to be able to compile it?

**Comment by nunotexbsd** [comment]
No, I can't run it:
`./cast2gif: Exec format error. Binary file not executable.`
`file cast2gif`
`cast2gif: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=4d1942776bbd57130cabf8e91bb50e2d733ddb32, stripped`
A FreeBSD binary is something like:
` ELF 64-bit LSB shared object, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 12.1, FreeBSD-style, stripped`

Well, I have FreeBSD port complete and I will submit it today and get more people testing.

Thanks

**Comment by nunotexbsd** [comment]
[cast2gif FreeBSD port submited](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=251064)! Lets wait until it get merged.

**Comment by zicklag** [comment]
Oh, interesting. I don't really know anything about FreeBSD, but I guess it has like a different executable format or something?

> Well, I have FreeBSD port complete and I will submit it today and get more people testing.

Cool! How did you port it? Did you get it to compile on FreeBSD, or did you modify the executable somehow?

> cast2gif FreeBSD port submited! Lets wait until it get merged.

:smiley: :+1:

**Comment by nunotexbsd** [comment]
Hi,

FreeBSD ports uses Makefiles to automate compilation/instalation and building packages:

- [Chapter 3. Quick Porting](https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/quick-porting.html)
- [6.4. Creating a Port for a Simple Rust Application](https://www.freebsd.org/doc/en_US.ISO8859-1/books/porters-handbook/building.html#cargo-ex1)

Well FreeBSD documentation is one of the things that I love most! And we have the best [handbook](https://www.freebsd.org/doc/en_US.ISO8859-1/books/handbook/) that I know compared to other OSes :)

[FreeBSD Documentation](https://www.freebsd.org/docs.html)

**Comment by zicklag** [comment]
Very cool! Thanks for doing that. I hope it helps others who use FreeBSD. :)

**Comment by zicklag** [comment]
@nunotexbsd I'm closing this as your port was merged. Thanks for setting that up!

Feel free to open a new issue if there are any problems. :smiley:
