### ISSUE TITLE
Option to force output terminal size to smaller value

### ISSUE THREAD

**Issue by JakeWharton** [katharostech/cast2gif#9]
The asciinema JSON value represents my terminal, but I often want to truncate the output to a subset in which the content actually appears for a smaller size image.

**Comment by zicklag** [comment]
So you are saying that you would like to be able to create a gif that only has a subset of the cells that were in the original recording?

Essentially like a rectangular zone of cells that you could specify by a height, width, x-offset, and y-offset that is used to crop the recording while generating the gif?

**Comment by JakeWharton** [comment]
Yep!

If my terminal window is large and I want to show the output of `ls`, as a contrived example, it probably only occupies 50 characters wide and 10 characters tall. But my terminal window is something like 300 wide and 50 tall resulting in a gif that is mostly dead space.

**Comment by zicklag** [comment]
OK, cool, what do you think of a CLI flag like this?

```
cast2gif in.cast out.gif --crop top=0,left=0,width=50=height=10
```

**Comment by JakeWharton** [comment]
Sure! That works.

**Comment by zicklag** [comment]
There you go, I made a new release that should work! Let me know how it goes.
